libview: Update loaded_document if the encrypted document loads
We found a crash when opening encrypted pdf files after commit
062473632b32 ("Do not load documents from pps_document_factory functions").
`priv->loaded_document` should be updated if we successfully load the
document.

```console
thread 'main' panicked at shell/src/window.rs:863:66:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at library/core/src/panicking.rs:218:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x5d3dc8d699ae - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h01335b120f10a173
   1:     0x5d3dc8d8e2b3 - core::fmt::write::hae7f4d812dd997ff
   2:     0x5d3dc8d65463 - std::io::Write::write_fmt::h71c148656f8ecfb4
   3:     0x5d3dc8d697f2 - std::sys::backtrace::BacktraceLock::print::ha36866943e50b285
   4:     0x5d3dc8d6a894 - std::panicking::default_hook::{{closure}}::h120972094b1addb6
   5:     0x5d3dc8d6a672 - std::panicking::default_hook::h48776a4e6f63486c
   6:     0x5d3dc8d6afe2 - std::panicking::rust_panic_with_hook::hae94debc1194f829
   7:     0x5d3dc8d6ad56 - std::panicking::begin_panic_handler::{{closure}}::hebc6f080bf37d09a
   8:     0x5d3dc8d69ee9 - std::sys::backtrace::__rust_end_short_backtrace::hb7cf2b18d55cb87e
   9:     0x5d3dc8d6aa1f - rust_begin_unwind
  10:     0x5d3dc811d08c - core::panicking::panic_nounwind_fmt::h4183847acfdb7b84
  11:     0x5d3dc811d11b - core::panicking::panic_nounwind::h5f546ab3b094a1c8
  12:     0x5d3dc811d2c6 - core::panicking::panic_cannot_unwind::hecd80579e1084ff3
  13:     0x5d3dc84727ed - papers_view::auto::job::JobExt::connect_finished::finished_trampoline::h1bb28a4dd4a0306d
                               at /data/source/papers/rust/papers-view/src/auto/job.rs:149:9
  14:     0x7a6c80a04210 - g_closure_invoke
  15:     0x7a6c80a18963 - <unknown>
  16:     0x7a6c80a1a37c - <unknown>
  17:     0x7a6c80a201f6 - g_signal_emit_valist
  18:     0x7a6c80a202bb - g_signal_emit
  19:     0x7a6c8084fb23 - emit_finished
                               at /data/source/papers/build/../libview/pps-job.c:136:3
  20:     0x7a6c808f0f7c - <unknown>
  21:     0x7a6c808f32a5 - <unknown>
  22:     0x7a6c808f54d7 - <unknown>
  23:     0x7a6c808f5c40 - g_main_context_iteration
  24:     0x7a6c80b32d75 - g_application_run
  25:     0x5d3dc827ca2e - gio::application::ApplicationExtManual::run_with_args::habf4d91e29c08bff
                               at /data/source/papers/build/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/gio-0.20.9/src/application.rs:29:13
  26:     0x5d3dc827cb19 - gio::application::ApplicationExtManual::run::h889d9930915b1507
                               at /data/source/papers/build/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/gio-0.20.9/src/application.rs:22:9
  27:     0x5d3dc83744fd - papers::main::h7d9ff3f57a2d24e6
                               at /data/source/papers/shell/src/main.rs:57:5
			         28:     0x5d3dc83071cb - core::ops::function::FnOnce::call_once::h0ecc954560c5d0b0
                               at /usr/lib/rust/1.85.1/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  29:     0x5d3dc81322be - std::sys::backtrace::__rust_begin_short_backtrace::h1889ab9b84f56fc9
                               at /usr/lib/rust/1.85.1/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  30:     0x5d3dc81500d1 - std::rt::lang_start::{{closure}}::h0aeaf8e9a7d9b5b0
                               at /usr/lib/rust/1.85.1/lib/rustlib/src/rust/library/std/src/rt.rs:195:18
  31:     0x5d3dc8d5e447 - std::rt::lang_start_internal::h3a0ebe45b8521e47
  32:     0x5d3dc81500aa - std::rt::lang_start::h61679e6fdb4d118e
                               at /usr/lib/rust/1.85.1/lib/rustlib/src/rust/library/std/src/rt.rs:194:17
  33:     0x5d3dc8374b9e - main
  34:     0x7a6c8055c42e - <unknown>
  35:     0x7a6c8055c4e9 - __libc_start_main
  36:     0x5d3dc811d8a5 - _start
  37:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
```

Fixes: 062473632b32 ("Do not load documents from pps_document_factory functions")