shell: Enable digital signing action when document supports
When opening a comic and click "Sign Digitally...", papers crashes.

```console
thread 'main' panicked at shell/src/document_view/io.rs:522:14:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(cherry picked from commit 6c4be0eed15d0dc19e6fdfdefd67575a206c09a8)